Refactor the logic of adding sort values during ajax call.
Whenever a user selected Event in Content Type, the sorting options would have been updated by ajax called defined in https://github.com/goalgorilla/open_social/blob/11.5.9/modules/social_features/social_content_block/src/ContentBuilder.php#L302

The sort values being fetched in https://github.com/goalgorilla/open_social/blob/11.5.9/modules/social_features/social_content_block/src/ContentBuilder.php#L385 were returning `NULL` due to which current widget options were also being set to `NULL` in https://github.com/goalgorilla/open_social/blob/11.5.9/modules/social_features/social_content_block/src/ContentBuilder.php#L387

This lead to an error in https://github.com/goalgorilla/open_social/blob/11.5.9/modules/social_features/social_content_block/src/ContentBuilder.php#L395 which crashed the AJAX.

Error:

```
TypeError: key(): Argument #1 ($array) must be of type array, null given in key() (line 411 of /var/www/html/profiles/contrib/social/modules/social_features/social_content_block/src/ContentBuilder.php)
```

So, we refactored the logic which made it possible to fetch the correct sorting options and set the updated values.