Issue #3266571 by szato, Ressinel: Fix fatal error
TypeError: Argument 1 passed to Drupal\social_activity\EmailTokenServices::__construct() must be an instance of Drupal\Core\Entity\EntityTypeManagerInterface instead of Drupal\webprofiler\Entity\EntityManager.