Fix several issues with assertions because Symfony request get returns bool|float|int|string|null.
Error: Parameter #1 $uuid of static method Drupal\Component\Uuid\Uuid::isValid() expects string, bool|float|int|string|null given.
Error: Parameter #1 $url of method Drupal\url_embed\UrlEmbed::getUrlInfo() expects string, bool|float|int|string|null given.
Error: Parameter #1 $text of static method Drupal\Core\Link::fromTextAndUrl() expects array|Drupal\Component\Render\MarkupInterface|string, bool|float|int|string|null given.
Error: Parameter #1 $uri of static method Drupal\Core\Url::fromUri() expects string, bool|float|int|string|null given.